import { useState, useEffect } from 'react';
import { intelligenceApi } from '../../lib/api';
import { renderMarkdown } from '../../lib/intelligenceMarkdown';
import IntelligenceErrorBanner from './IntelligenceErrorBanner';

/**
 * NarrativePanel — renders an AI-generated markdown narrative for a dataset.
 *
 * Props:
 *   datasetId        (string)  — the active dataset's ID
 *   initialNarrative (object?) — { fullMarkdown, tone } if already loaded
 */
export default function NarrativePanel({ datasetId, initialNarrative }) {
  const [narrative, setNarrative] = useState(initialNarrative ?? null);
  const [tone, setTone] = useState(initialNarrative?.tone ?? 'executive');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Determine if the error hides regenerate controls
  const hideRegenerate =
    error?.code === 'LLM_NOT_CONFIGURED' ||
    error?.code === 'INTELLIGENCE_DISABLED';

  // Sync the rendered narrative when the active dataset (and therefore its
  // persisted narrative) changes. We do NOT auto-fetch when no narrative
  // exists — generation must be triggered explicitly to avoid burning LLM
  // quota on every page visit.
  useEffect(() => {
    setNarrative(initialNarrative ?? null);
    setTone(initialNarrative?.tone ?? 'executive');
    setError(null);
  }, [datasetId, initialNarrative]);

  async function fetchNarrative(selectedTone) {
    setLoading(true);
    setError(null);
    try {
      const data = await intelligenceApi.narrative(datasetId, { tone: selectedTone });
      setNarrative(data);
      setTone(selectedTone);
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  }

  const handleToneChange = (newTone) => {
    if (newTone === tone && narrative) return;
    setTone(newTone);
    fetchNarrative(newTone);
  };

  const handleRegenerate = () => {
    fetchNarrative(tone);
  };

  return (
    <div className="bg-surface-container-low rounded-2xl border border-primary/20 p-6 lg:p-8 shadow-xl shadow-primary/5 space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <span
            className="material-symbols-outlined text-primary text-2xl"
            style={{ fontVariationSettings: "'FILL' 1" }}
          >
            auto_awesome
          </span>
          <div>
            <h2 className="text-xl font-bold font-headline tracking-tight">AI Narrative</h2>
            <p className="text-xs text-on-surface-variant">Generated by the Intelligence Layer</p>
          </div>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          {/* Tone toggle */}
          <div className="flex rounded-lg border border-outline-variant/20 overflow-hidden text-xs font-semibold">
            {['executive', 'technical'].map((t) => (
              <button
                key={t}
                onClick={() => handleToneChange(t)}
                disabled={loading}
                className={`px-3 py-1.5 capitalize transition-colors disabled:opacity-50 cursor-pointer ${
                  tone === t
                    ? 'bg-primary text-on-primary'
                    : 'bg-surface-container text-on-surface-variant hover:text-on-surface'
                }`}
              >
                {t}
              </button>
            ))}
          </div>

          {/* Regenerate button */}
          {!hideRegenerate && (
            <button
              onClick={handleRegenerate}
              disabled={loading}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-surface-container border border-outline-variant/20 text-on-surface-variant hover:text-on-surface hover:border-primary/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <>
                  <Spinner />
                  Generating…
                </>
              ) : (
                <>
                  <span className="material-symbols-outlined text-xs">{narrative ? 'refresh' : 'auto_awesome'}</span>
                  {narrative ? 'Regenerate' : 'Generate Narrative'}
                </>
              )}
            </button>
          )}
        </div>
      </div>

      {/* Error */}
      {error && <IntelligenceErrorBanner error={error} />}

      {/* Loading skeleton */}
      {loading && !narrative && (
        <div className="space-y-3 animate-pulse">
          {[80, 60, 90, 50, 70].map((w, i) => (
            <div
              key={i}
              className="h-3 bg-surface-container-high rounded-full"
              style={{ width: `${w}%` }}
            />
          ))}
        </div>
      )}

      {/* Empty state — narrative not yet generated */}
      {!loading && !narrative && !error && (
        <div className="flex flex-col items-center justify-center gap-3 py-8 text-center text-on-surface-variant">
          <span className="material-symbols-outlined text-3xl opacity-40">auto_awesome</span>
          <p className="text-sm max-w-md">
            No AI narrative yet for this dataset. Click Generate Narrative above to write an
            {tone === 'technical' ? ' in-depth technical' : ' executive'} summary from your stats.
          </p>
        </div>
      )}

      {/* Narrative content */}
      {narrative?.fullMarkdown && (
        <div
          className="prose prose-invert prose-sm max-w-none text-on-surface-variant leading-relaxed
            [&_h1]:text-on-surface [&_h1]:font-headline [&_h1]:text-xl [&_h1]:font-bold [&_h1]:mb-2
            [&_h2]:text-on-surface [&_h2]:font-headline [&_h2]:text-lg [&_h2]:font-bold [&_h2]:mt-5 [&_h2]:mb-2
            [&_h3]:text-on-surface [&_h3]:font-semibold [&_h3]:mt-4 [&_h3]:mb-1
            [&_h4]:text-on-surface [&_h4]:font-semibold [&_h4]:mt-3 [&_h4]:mb-1
            [&_p]:mb-3 [&_p]:text-sm
            [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-3 [&_ul]:space-y-1
            [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-3 [&_ol]:space-y-1
            [&_li]:text-sm
            [&_strong]:text-on-surface [&_strong]:font-semibold
            [&_em]:italic
            [&_code]:bg-surface-container [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-xs [&_code]:font-mono [&_code]:text-primary
            [&_blockquote]:border-l-2 [&_blockquote]:border-primary/40 [&_blockquote]:pl-4 [&_blockquote]:italic [&_blockquote]:text-on-surface-variant
            [&_a]:text-primary [&_a]:underline [&_a]:underline-offset-2"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(narrative.fullMarkdown) }}
        />
      )}

      {/* Metadata footer */}
      {narrative?.generatedAt && (
        <p className="text-[10px] text-on-surface-variant/50 uppercase tracking-widest">
          Generated {new Date(narrative.generatedAt).toLocaleString()} · {narrative.model || 'AI'}
        </p>
      )}
    </div>
  );
}

function Spinner() {
  return (
    <span className="w-3.5 h-3.5 rounded-full border-2 border-on-surface-variant/30 border-t-on-surface-variant animate-spin" />
  );
}
